server:
  port: 8086

spring:
  application:
    name: feedback-service
  data:
    mongodb:
      uri: mongodb://skillsync:skillsync123@localhost:27017/skillsync?authSource=admin
  rabbitmq:
    host: localhost
    port: 5672
    username: skillsync
    password: skillsync123

jwt:
  secret: ${JWT_SECRET:mySecretKeyForSkillSyncPlatformThatIsLongEnough}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.skillsync.feedback: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://skillsync:skillsync123@mongodb:27017/skillsync?authSource=admin
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: skillsync
    password: skillsync123